<?php

use think\migration\Seeder;

class AdminInit extends Seeder
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $table = $this->table('admin');
        $data = [
            [
                "id" => null,
                "username" => "admin",
                "password" => '$argon2i$v=19$m=65536,t=4,p=1$czNwT21yRHo5bWJBeThiOQ$zghwv1kcDJYC9FEa2AQwu4Nn0Gcles3c7PMpmxdHc8U',
                "salt" => "LEbxBkws",
                "nickname" => "系统管理员",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663558974-3989f02efe32482.png",
                "desc" => "系统杠霸子，统领整个系统所有功能",
                "phone" => "18888888888",
                "email" => "yulinzhihou@163.com",
                "extension" => "[]",
                "sort" => 1,
                "status" => 1,
                "login_ip" => "127.0.0.1",
                "create_time" => 1653899819,
                "update_time" => 1661831033
            ],[
                "id" => null,
                "username" => "mj",
                "password" => '$argon2i$v=19$m=65536,t=4,p=1$d2dmOE5XZUlOck1WamdFbg$3JTk5yyRq/c036qAJXciIKfjiVi8y0gb3XIcivYtuJU',
                "salt" => "AtwfeCnZoU",
                "nickname" => "明教",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834430-5626543419730bf.jpg.webp",
                "desc" => "明教弟子外功攻击位列十四大门派之首，同时带有圣火的灼伤效果，武功先发制人，而自带的复活能力也常使他们反败为胜。",
                "phone" => "test",
                "email" => "test",
                "extension" => "[]",
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 1661831025,
                "update_time" => 1661831025
            ],[
                "id" => null,
                "username" => "sl",
                "password" => '$argon2i$v=19$m=65536,t=4,p=1$ZEtEeklvbUFzUkp6VVNtTg$875aWpnR+OJjhRd5cp9TErv2fwmladNfQYFYBBMVXhc',
                "salt" => "WhLupSQcn",
                "nickname" => "少林",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834443-436c70d57695684.jpg.webp",
                "desc" => "少林弟子武功底蕴深厚，外家功夫天下第一，面对威胁时往往舍生取义，掩护同伴，是战友们最可靠的屏障。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 0,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 1663677982,
                "update_time" => 1663677982
            ],[
                "id" => null,
                "username" => "mr",
                "password" => '$argon2i$v=19$m=65536,t=4,p=1$dmdqQ0UycWVDeUEuSGdkNQ$Gcm60RoVc16b7jZeMq9joUI04cUuwJyR3vif100CbZw',
                "salt" => "xLtrAdlQCu",
                "nickname" => "慕容",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834436-7f86af7b060e9dc.jpg.webp",
                "desc" => "慕容世家弟子内功深厚，招式精奇，家传'以彼之道还施彼身'之术借力打力，常常会令对手惊愕无比，从而反败为胜。",
                "phone" => "12312312312",
                "email" => "wefkjfwkj@lkdf.om",
                "extension" => null,
                "sort" => 3,
                "status" => 1,
                "login_ip" => "127.0.0.1",
                "create_time" => 1663818721,
                "update_time" => 1663829378
              ],[
                "id" => null,
                "username" => "gg",
                "password" => "",
                "salt" => "",
                "nickname" => "鬼谷",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834424-243c24f3c4d1850.jpg.webp",
                "desc" => "鬼谷一门，始于春秋战国。弟子主修纵横权谋之数，折冲樽俎之间，决胜千里之外，以一己之力左右天下大势。另外，鬼谷弟子于星象、丹药、奇门八卦、武学亦有研究。战国之后，鬼谷一门自认其所学祸乱天下，苍生无辜，遂自封其门隐于世间，长达千年。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "ts",
                "password" => "",
                "salt" => "",
                "nickname" => "天山",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834461-a1e8767d8d08d50.jpg.webp",
                "desc" => "天山弟子的武功以诡异著称，是天生的刺客，战斗中身形飘忽，可以瞬间隐没自己，待合适时机爆发，实行一击必杀。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "em",
                "password" => "",
                "salt" => "",
                "nickname" => "峨眉",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834326-db5ea628b087cff.jpg.webp",
                "desc" => "峨嵋弟子是十四大门派中唯一的治疗单位，同时拥有强大的攻击力与自保能力，一定时间内甚至能刀枪不入，无敌于阵前。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "xx",
                "password" => "",
                "salt" => "",
                "nickname" => "星宿",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834472-3b1d6860675a5dc.jpg.webp",
                "desc" => "星宿弟子是名门正派天生的敌人，用毒之术精深无比，与他们对战，容易被扰乱心智恐惧不已，更需忍受持续的剧毒伤害。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "xy",
                "password" => "",
                "salt" => "",
                "nickname" => "逍遥",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834480-0ff48148d8126ed.jpg.webp",
                "desc" => "逍遥弟子武功博大精深，奇门遁甲控敌之术无敌于天下，神出鬼没让敌人防不胜防，群战中更是令人胆寒。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "tl",
                "password" => "",
                "salt" => "",
                "nickname" => "天龙",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834449-113fad02c7baafa.jpg.webp",
                "desc" => "天龙弟子内、外兼修，同时拥有数种攻击属性，以指为剑，命中极高，更可隔空点穴，制敌于数米之外。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "wd",
                "password" => "",
                "salt" => "",
                "nickname" => "武当",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834467-ec361b338a7c512.jpg.webp",
                "desc" => "武当弟子道法深厚，武功博大雄浑，内功位列十四大门派之首，攻敌于百步之外，同时可以移形换位，几乎能做到敌不沾身。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "gb",
                "password" => "",
                "salt" => "",
                "nickname" => "丐帮",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834365-f6ed58552687716.jpg.webp",
                "desc" => "丐帮弟子擅长近身搏击，腾挪闪避之术天下无双，连击越多，攻击力越大，战斗中往往愈战愈强，后发制人。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "thd",
                "password" => "",
                "salt" => "",
                "nickname" => "桃花岛",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834552-31724aab18e3952.jpg.webp",
                "desc" => "桃花岛立派先祖为江南李氏幼女：李沧海，自幼聪慧。早年，她曾陪伴自己的姐姐李秋水拜师于逍遥子门下，并且与姐姐一同对自己的师兄无崖子产生了倾慕之心。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "jpg",
                "password" => "",
                "salt" => "",
                "nickname" => "绝情谷",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834545-fbd57f3cd37a6d5.png.webp",
                "desc" => "绝情谷不争“武林盟主”之类的虚名，不追求武学境界的“天下第一”，更在乎自己的理想，门派的主旨是否实现。因此对于许多武林流传多年的陈冗规矩不予遵守，不参与竞争，和其他十三门派略微有些不同。与原有的“武林”相比，更接近于“江湖”，更接地气",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "tm",
                "password" => "",
                "salt" => "",
                "nickname" => "唐门",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834456-e12355729d11cd9.jpg.webp",
                "desc" => "唐门弟子内劲强横，攻击之中多以内劲注入金石弩箭之中伤敌。同时又懂得淬毒之术，机关箭雨，一招一式都充满杀机，凌厉非凡。",
                "role_id" => 0,
                "phone" => "",
                "email" => "",
                "extension" => null,
                "sort" => 1,
                "status" => 1,
                "login_ip" => "",
                "create_time" => 0,
                "update_time" => 0
            ],[
                "id" => null,
                "username" => "test",
                "password" => '$argon2i$v=19$m=65536,t=4,p=1$ZEVQUDhLSWNJVWx5SVlnbw$saehUtcTIXtoY4eEU4Z/2YzZYV7Lfi/1tToJ0ExLrEA',
                "salt" => "Nyxju",
                "nickname" => "test",
                "avatar" => "https://ghproxy.com/https://raw.githubusercontent.com/yulinzhihou706/gsgameshare/master/wp-content/uploads/2022/09/1663834810-2431f9856ff3628.png.webp",
                "desc" => "体验账号",
                "phone" => "test",
                "email" => "test",
                "extension" => "[]",
                "sort" => 1,
                "status" => 1,
                "login_ip" => "127.0.0.1",
                "create_time" => 1661328982,
                "update_time" => 1661328990
            ]
        ];
        $table->insert($data)->saveData();
    }
}