<?php

use think\migration\Seeder;

class MenuInit extends Seeder
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $table = $this->table('menu');
        $str = <<<EOF
[
    {
      "id": 1,
      "pid": 0,
      "type": "menu",
      "title": "控制台",
      "name": "dashboard/dashboard",
      "path": "dashboard",
      "icon": "fa fa-dashboard",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/dashboard.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "remark_text",
      "weigh": 999,
      "status": "1",
      "update_time": 1651926966,
      "create_time": 1646889188
    },
    {
      "id": 2,
      "pid": 0,
      "type": "menu_dir",
      "title": "权限管理",
      "name": "auth",
      "path": "auth",
      "icon": "fa fa-group",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 100,
      "status": "1",
      "update_time": 1648948034,
      "create_time": 1645876529
    },
    {
      "id": 3,
      "pid": 2,
      "type": "menu",
      "title": "角色组管理",
      "name": "auth/group",
      "path": "auth/group",
      "icon": "fa fa-group",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/auth/group/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 99,
      "status": "1",
      "update_time": 1648162157,
      "create_time": 1646927597
    },
    {
      "id": 4,
      "pid": 3,
      "type": "button",
      "title": "查看",
      "name": "auth/group/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 99,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 5,
      "pid": 3,
      "type": "button",
      "title": "添加",
      "name": "auth/group/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 99,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 6,
      "pid": 3,
      "type": "button",
      "title": "编辑",
      "name": "auth/group/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 99,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806129
    },
    {
      "id": 7,
      "pid": 3,
      "type": "button",
      "title": "删除",
      "name": "auth/group/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 99,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 8,
      "pid": 2,
      "type": "menu",
      "title": "管理员管理",
      "name": "auth/admin",
      "path": "auth/admin",
      "icon": "el-icon-UserFilled",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/auth/admin/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 98,
      "status": "1",
      "update_time": 1648067239,
      "create_time": 1647549566
    },
    {
      "id": 9,
      "pid": 8,
      "type": "button",
      "title": "查看",
      "name": "auth/admin/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 98,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 10,
      "pid": 8,
      "type": "button",
      "title": "添加",
      "name": "auth/admin/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 98,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 11,
      "pid": 8,
      "type": "button",
      "title": "编辑",
      "name": "auth/admin/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 98,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806129
    },
    {
      "id": 12,
      "pid": 8,
      "type": "button",
      "title": "删除",
      "name": "auth/admin/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 98,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 13,
      "pid": 2,
      "type": "menu",
      "title": "菜单规则管理",
      "name": "auth/menu",
      "path": "auth/menu",
      "icon": "el-icon-Grid",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/auth/menu/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 97,
      "status": "1",
      "update_time": 1648133759,
      "create_time": 1645876529
    },
    {
      "id": 14,
      "pid": 13,
      "type": "button",
      "title": "查看",
      "name": "auth/menu/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 97,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 15,
      "pid": 13,
      "type": "button",
      "title": "添加",
      "name": "auth/menu/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 97,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 16,
      "pid": 13,
      "type": "button",
      "title": "编辑",
      "name": "auth/menu/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 97,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806129
    },
    {
      "id": 17,
      "pid": 13,
      "type": "button",
      "title": "删除",
      "name": "auth/menu/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 97,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 18,
      "pid": 13,
      "type": "button",
      "title": "快速排序",
      "name": "auth/menu/sortable",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 97,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 19,
      "pid": 2,
      "type": "menu",
      "title": "管理员日志管理",
      "name": "auth/adminLog",
      "path": "auth/adminLog",
      "icon": "el-icon-List",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/auth/adminLog/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 96,
      "status": "1",
      "update_time": 1648067241,
      "create_time": 1647963918
    },
    {
      "id": 20,
      "pid": 19,
      "type": "button",
      "title": "查看",
      "name": "auth/adminLog/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 96,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 21,
      "pid": 0,
      "type": "menu_dir",
      "title": "会员管理",
      "name": "user",
      "path": "user",
      "icon": "fa fa-drivers-license",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 95,
      "status": "1",
      "update_time": 1648947448,
      "create_time": 1648049553
    },
    {
      "id": 22,
      "pid": 21,
      "type": "menu",
      "title": "会员管理",
      "name": "user/user",
      "path": "user/user",
      "icon": "fa fa-user",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/user/user/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 94,
      "status": "1",
      "update_time": 1648255019,
      "create_time": 1648049712
    },
    {
      "id": 23,
      "pid": 22,
      "type": "button",
      "title": "查看",
      "name": "user/user/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 94,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 24,
      "pid": 22,
      "type": "button",
      "title": "添加",
      "name": "user/user/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 94,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 25,
      "pid": 22,
      "type": "button",
      "title": "编辑",
      "name": "user/user/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 94,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806129
    },
    {
      "id": 26,
      "pid": 22,
      "type": "button",
      "title": "删除",
      "name": "user/user/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 94,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 27,
      "pid": 21,
      "type": "menu",
      "title": "会员分组管理",
      "name": "user/group",
      "path": "user/group",
      "icon": "fa fa-group",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/user/group/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 93,
      "status": "1",
      "update_time": 1648067248,
      "create_time": 1648051141
    },
    {
      "id": 28,
      "pid": 27,
      "type": "button",
      "title": "查看",
      "name": "user/group/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 93,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 29,
      "pid": 27,
      "type": "button",
      "title": "添加",
      "name": "user/group/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 93,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 30,
      "pid": 27,
      "type": "button",
      "title": "编辑",
      "name": "user/group/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 93,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806129
    },
    {
      "id": 31,
      "pid": 27,
      "type": "button",
      "title": "删除",
      "name": "user/group/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 93,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 32,
      "pid": 21,
      "type": "menu",
      "title": "会员规则管理",
      "name": "user/rule",
      "path": "user/rule",
      "icon": "fa fa-th-list",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/user/rule/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 92,
      "status": "1",
      "update_time": 1648067247,
      "create_time": 1648051207
    },
    {
      "id": 33,
      "pid": 32,
      "type": "button",
      "title": "查看",
      "name": "user/rule/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 92,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 34,
      "pid": 32,
      "type": "button",
      "title": "添加",
      "name": "user/rule/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 92,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 35,
      "pid": 32,
      "type": "button",
      "title": "编辑",
      "name": "user/rule/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 92,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806129
    },
    {
      "id": 36,
      "pid": 32,
      "type": "button",
      "title": "删除",
      "name": "user/rule/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 92,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 37,
      "pid": 32,
      "type": "button",
      "title": "快速排序",
      "name": "user/rule/sortable",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 92,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 38,
      "pid": 21,
      "type": "menu",
      "title": "会员余额管理",
      "name": "user/moneyLog",
      "path": "user/moneyLog",
      "icon": "el-icon-Money",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/user/moneyLog/index.vue",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 91,
      "status": "1",
      "update_time": 1648437356,
      "create_time": 1648052587
    },
    {
      "id": 39,
      "pid": 38,
      "type": "button",
      "title": "查看",
      "name": "user/moneyLog/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 91,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 40,
      "pid": 38,
      "type": "button",
      "title": "添加",
      "name": "user/moneyLog/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 91,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 41,
      "pid": 21,
      "type": "menu",
      "title": "会员积分管理",
      "name": "user/scoreLog",
      "path": "user/scoreLog",
      "icon": "el-icon-Discount",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/user/scoreLog/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 90,
      "status": "1",
      "update_time": 1648067246,
      "create_time": 1648052689
    },
    {
      "id": 42,
      "pid": 41,
      "type": "button",
      "title": "查看",
      "name": "user/scoreLog/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 90,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 43,
      "pid": 41,
      "type": "button",
      "title": "添加",
      "name": "user/scoreLog/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 90,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 44,
      "pid": 0,
      "type": "menu_dir",
      "title": "常规管理",
      "name": "routine",
      "path": "routine",
      "icon": "fa fa-cogs",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 89,
      "status": "1",
      "update_time": 1648133739,
      "create_time": 1645876529
    },
    {
      "id": 45,
      "pid": 44,
      "type": "menu",
      "title": "系统配置",
      "name": "routine/config",
      "path": "routine/config",
      "icon": "el-icon-Tools",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/routine/config/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 88,
      "status": "1",
      "update_time": 1648781089,
      "create_time": 1648053389
    },
    {
      "id": 46,
      "pid": 45,
      "type": "button",
      "title": "查看",
      "name": "routine/config/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 88,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 47,
      "pid": 45,
      "type": "button",
      "title": "编辑",
      "name": "routine/config/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 88,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 48,
      "pid": 44,
      "type": "menu",
      "title": "附件管理",
      "name": "routine/attachment",
      "path": "routine/attachment",
      "icon": "fa fa-folder",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/routine/attachment/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "remark_text",
      "weigh": 87,
      "status": "1",
      "update_time": 1648067228,
      "create_time": 1647105410
    },
    {
      "id": 49,
      "pid": 48,
      "type": "button",
      "title": "查看",
      "name": "routine/attachment/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 87,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 50,
      "pid": 48,
      "type": "button",
      "title": "编辑",
      "name": "routine/attachment/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 87,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806129
    },
    {
      "id": 51,
      "pid": 48,
      "type": "button",
      "title": "删除",
      "name": "routine/attachment/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 87,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 52,
      "pid": 44,
      "type": "menu",
      "title": "个人资料",
      "name": "routine/adminInfo",
      "path": "routine/adminInfo",
      "icon": "fa fa-user",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/routine/adminInfo.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 86,
      "status": "1",
      "update_time": 1648067229,
      "create_time": 1645876529
    },
    {
      "id": 53,
      "pid": 52,
      "type": "button",
      "title": "查看",
      "name": "routine/adminInfo/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 86,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 54,
      "pid": 52,
      "type": "button",
      "title": "编辑",
      "name": "routine/adminInfo/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 86,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806129
    },
    {
      "id": 55,
      "pid": 0,
      "type": "menu_dir",
      "title": "数据安全管理",
      "name": "security",
      "path": "security",
      "icon": "fa fa-shield",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 85,
      "status": "1",
      "update_time": 1649853629,
      "create_time": 1648948025
    },
    {
      "id": 56,
      "pid": 55,
      "type": "menu",
      "title": "数据回收站",
      "name": "security/dataRecycleLog",
      "path": "security/dataRecycleLog",
      "icon": "fa fa-database",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/security/dataRecycleLog/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 84,
      "status": "1",
      "update_time": 1651603319,
      "create_time": 1648948283
    },
    {
      "id": 57,
      "pid": 56,
      "type": "button",
      "title": "查看",
      "name": "security/dataRecycleLog/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 84,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 58,
      "pid": 56,
      "type": "button",
      "title": "删除",
      "name": "security/dataRecycleLog/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 84,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 59,
      "pid": 56,
      "type": "button",
      "title": "还原",
      "name": "security/dataRecycleLog/restore",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 84,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 60,
      "pid": 56,
      "type": "button",
      "title": "查看详情",
      "name": "security/dataRecycleLog/info",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 84,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 61,
      "pid": 55,
      "type": "menu",
      "title": "敏感数据修改记录",
      "name": "security/sensitiveDataLog",
      "path": "security/sensitiveDataLog",
      "icon": "fa fa-expeditedssl",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/security/sensitiveDataLog/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 83,
      "status": "1",
      "update_time": 1649112262,
      "create_time": 1649059604
    },
    {
      "id": 62,
      "pid": 61,
      "type": "button",
      "title": "查看",
      "name": "security/sensitiveDataLog/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 83,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 63,
      "pid": 61,
      "type": "button",
      "title": "删除",
      "name": "security/sensitiveDataLog/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 83,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 64,
      "pid": 61,
      "type": "button",
      "title": "回滚",
      "name": "security/sensitiveDataLog/rollback",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 83,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 65,
      "pid": 61,
      "type": "button",
      "title": "查看详情",
      "name": "security/sensitiveDataLog/info",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 83,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 66,
      "pid": 55,
      "type": "menu",
      "title": "数据回收规则管理",
      "name": "security/dataRecycle",
      "path": "security/dataRecycle",
      "icon": "fa fa-database",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/security/dataRecycle/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "在此定义需要回收的数据，实现数据自动统一回收",
      "weigh": 82,
      "status": "1",
      "update_time": 1651603319,
      "create_time": 1648948215
    },
    {
      "id": 67,
      "pid": 66,
      "type": "button",
      "title": "查看",
      "name": "security/dataRecycle/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 82,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 68,
      "pid": 66,
      "type": "button",
      "title": "添加",
      "name": "security/dataRecycle/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 82,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 69,
      "pid": 66,
      "type": "button",
      "title": "编辑",
      "name": "security/dataRecycle/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 82,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806129
    },
    {
      "id": 70,
      "pid": 66,
      "type": "button",
      "title": "删除",
      "name": "security/dataRecycle/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 82,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 71,
      "pid": 55,
      "type": "menu",
      "title": "敏感字段规则管理",
      "name": "security/sensitiveData",
      "path": "security/sensitiveData",
      "icon": "fa fa-expeditedssl",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/security/sensitiveData/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "在此定义需要保护的敏感字段，随后系统将自动监听该字段的修改操作，并提供了敏感字段的修改回滚功能",
      "weigh": 81,
      "status": "1",
      "update_time": 1649112263,
      "create_time": 1649005119
    },
    {
      "id": 72,
      "pid": 71,
      "type": "button",
      "title": "查看",
      "name": "security/sensitiveData/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 81,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 73,
      "pid": 71,
      "type": "button",
      "title": "添加",
      "name": "security/sensitiveData/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 81,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 74,
      "pid": 71,
      "type": "button",
      "title": "编辑",
      "name": "security/sensitiveData/edit",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 81,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806129
    },
    {
      "id": 75,
      "pid": 71,
      "type": "button",
      "title": "删除",
      "name": "security/sensitiveData/del",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 81,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 76,
      "pid": 0,
      "type": "menu",
      "title": "BuildAdmin",
      "name": "buildadmin/buildadmin",
      "path": "buildadmin",
      "icon": "local-logo",
      "menu_type": "link",
      "url": "https://doc.buildadmin.com",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 0,
      "status": "0",
      "update_time": 1651926977,
      "create_time": 1648947396
    },
    {
      "id": 77,
      "pid": 45,
      "type": "button",
      "title": "添加",
      "name": "routine/config/add",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 88,
      "status": "1",
      "update_time": 1655375826,
      "create_time": 1655375812
    },
    {
      "id": 78,
      "pid": 0,
      "type": "menu",
      "title": "模块市场",
      "name": "moduleStore/moduleStore",
      "path": "moduleStore",
      "icon": "el-icon-GoodsFilled",
      "menu_type": "tab",
      "url": "",
      "component": "/src/views/backend/module/index.vue",
      "keep_alive": 1,
      "extend": "none",
      "remark": "",
      "weigh": 86,
      "status": "1",
      "update_time": 1661317584,
      "create_time": 1661317424
    },
    {
      "id": 79,
      "pid": 78,
      "type": "button",
      "title": "查看",
      "name": "moduleStore/moduleStore/index",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 1,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 80,
      "pid": 78,
      "type": "button",
      "title": "安装",
      "name": "moduleStore/moduleStore/install",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 2,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 81,
      "pid": 78,
      "type": "button",
      "title": "调整状态",
      "name": "moduleStore/moduleStore/changeState",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 3,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 82,
      "pid": 78,
      "type": "button",
      "title": "卸载",
      "name": "moduleStore/moduleStore/uninstall",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 4,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    },
    {
      "id": 83,
      "pid": 78,
      "type": "button",
      "title": "更新",
      "name": "moduleStore/moduleStore/update",
      "path": "",
      "icon": "",
      "menu_type": null,
      "url": "",
      "component": "",
      "keep_alive": 0,
      "extend": "none",
      "remark": "",
      "weigh": 5,
      "status": "1",
      "update_time": 1648065864,
      "create_time": 1647806112
    }
  ]
EOF;

        $data = json_decode($str,true);
        $table->insert($data)->saveData();
    }
}
